version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.15.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false